keycloak/keycloak-web

src/main/resources/extensions/client-authorization.json
src/main/resources/extensions/export-endpoint.json
src/main/resources/extensions/wsfed-protocol.json

As suggested in the keycloak user mailing list [here](http://lists.jboss.org/pipermail/keycloak-user/2018-August/015125.html), and the keycloak dev mailing list [here](http://lists.jboss.org/pipermail/keycloak-dev/2018-August/011114.html), I'm submitting the descriptions of two modules developed for the cloudtrust project ("client authorization" and "full export endpoint") for the keycloak extensions page.

Extension descriptions for modules "client authorization" and "full export endpoint"

---

extensions/metrics-spi.json

Adds the [Metrics SPI](https://github.com/aerogear/keycloak-metrics-spi) to the list of community extensions.

add metrics spi to extensions

---

extensions/privacyidea-two-factor-authentication.json

privacyIDEA is a central 2FA system running on premise.
It can manage a lot of different token types for an organization.
The privacyidea keycloak extension enables those organizations to also use the enrolled tokens with keycloak.

Add entry about privacyIDEA 2FA

---

extensions/json-remote-claim.json

An extension to add a new mapper type to retrieve JSON data from a remote HTTP endpoint (e.g. from a REST API) and add it as a claim into tokens or user info.
Extension discussed there: https://issues.redhat.com/browse/KEYCLOAK-12286

Add json-remote-claim extension

---

extensions/keycloak-config-cli.json

Hi,
keycloak-config-cli is a Keycloak utility to ensure the desired configuration state for a realm based on a JSON file. The format of the JSON file based on the export realm format. Store and handle the configuration files inside git just like normal code. A Keycloak restart isn't required to apply the configuration.
Please add keycloak-config-cli to the list of community extensions page.

Add keycloak-config-cli

---

version-template.json

[KEYCLOAK-17432] Upgrade to Wildfly 23
Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>
_Note:_ Needs to be merged together with the following changes:
* [Code change](https://github.com/keycloak/keycloak/pull/7857)
* [Documentation change](https://github.com/keycloak/keycloak-documentation/pull/1145)

[KEYCLOAK-17432] Upgrade to Wildfly 23

---

static/schema/keycloak_saml_adapter_1_13.xsd

Add new Keycloak SAML adapter schema with defined _socketTimeout_, _connectionTimeout_ and _connectionTtl_ property for HTTP client.
JIRA: [KEYCLOAK-18466 Configure HTTP client timeouts for adapters](https://github.com/keycloak/keycloak/pull/8165)

KEYCLOAK-18466 New Keycloak SAML adapter schema

---

guides/getting-started/getting-started-kube.adoc

Those are additional fixes found testing out the fix for #192

Additional fixes for #192

---

templates/blog-release.ftl

The Link to GH issues always point to
https://github.com/issues?q=is%3Aissue+user%3Akeycloak+is%3Aclosed+milestone%3A{version.version}

Fixes Github link in releases

---

extensions/cas-login-protocol.json

Doccrazy stopped maintaining the extension, but there is a working fork.

extensions/cas-login-protocol: new maintainer and URL

---

extensions/testcontainers-keycloak.json

This is not really a Keycloak "extension", but IMHO a useful project the community should know about, thus adding it to the extensions page would be awesome.
The project already exists for 2 years and has ongoing download figures. From my experience and feedback from users, it's widely used across the community. Also, it's more or less "ready" for Keycloak.X, once it is released!

Add community extension "Testcontainers Keycloak"

---

blog/2021/apisix.adoc

Hi @stianst , I found some typo on the blog and modified them with this pull request.
Thanks @starsz for pointing them out this morning!
- Modified commands on the blog
- Removed a hanging `alt=Set Client type,width=640,height=350` description. This is meant to be deleted after transcription of markdown to acsiiDoc(Yet I forgot to do so). 
- Changed '**c**onfidential' to '**C**onfidential', in order to keep them the same as described in paragraphs above.

docs: update APISIX blog

---

templates/downloads-18.ftl

Closes #256
@stianst Could you please take a look at it?
We test only the most recent versions of Fuse 6 and Fuse 7. Current tested version of Fuse 6 is `6.3` and it's the last released minor version of it. Therefore, I think the version `6.2` could be removed, because we're not so sure if it's working with it. And for Fuse 7, current tested version is 7.10, but it's changing a lot, so it'd be better to define version `7.x`? Or just `7`? I'd like to avoid confusions with only specified version `7`, when it might be associated with Fuse `7.0`. On the other hand, with specifying `7.x`, it might be associated with the fact that it's working with each minor version of Fuse 7. @stianst WDYT?

Specify supported Fuse versions in downloads section

---

guides/getting-started/getting-started-podman.adoc
guides/getting-started/getting-started-zip.adoc
guides/includes/getting-started/create-admin-localhost.adoc
guides/includes/getting-started/next.adoc
guides/includes/getting-started/start-keycloak-container.adoc
guides/includes/getting-started/start-keycloak-localhost.adoc
guides/securing-apps/vue.adoc

The commands in the documentation are not working anymore 
e.g.
`docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:16.1.1 start-dev`
fails with following error
This PR reverts commit 7a6f19d7bab04deb6d43ceda22036396f00191b2. 
as it should be merged after release 17.0.0
https://github.com/keycloak/keycloak/issues/9309
@stianst  this fixes #271 and #272

Revert "Update getting started guides to Quarkus dist"

---

src/main/java/org/keycloak/webbuilder/builders/GuideBuilder.java
src/main/java/org/keycloak/webbuilder/builders/ResourcesBuilder.java

Adds support for the `images` folder coming from the `generated-guides`
Resolves #302

Support for images folder

---

extensions/apple-identity-provider.json

Added reference to an Apple Identity Provider extension.
See https://github.com/klausbetz/apple-identity-provider-keycloak/issues/9 @stianst

docs: add apple identity provider to extension list

---

extensions/events-helpers.json
extensions/gcpubsub-eventlistener.json
extensions/keycloak-python.json
extensions/magic-link.json
extensions/organizations.json

- Removed missing Google PubSub listener.
- Updated Python keycloak-client link to current.
- Added extensions for magic links, organizations, and event helpers.

Updates and additions to extensions section

---

templates/documentation-11.ftl
version-template.json
versions/19.0.0.json
versions/19.0.1.json
versions/19.0.2.json
versions/19.0.3.json
versions/20.0.0.json
versions/20.0.1.json

Closes #355
Turned out the new release process [publishes documentation](https://github.com/keycloak/keycloak.github.io/tree/main/docs) as three position version (e.g. `19.0.3`) instead of two (`19.0`). This makes sense from my perspective even though we link on the web just the minor versions (`19.0`) as it acts as a permalink to specific micro.

Broken links on archived documentation

---

blog/2022/fips.adoc

Hello,
Just adding a space between a back stick and a word to help syntax highlighting and readability.

Fix typo breaking syntax highlighting in fips blogpost

---

templates/downloads-archive-version.ftl

This is a screenshot of the reworked page from a local build:
* Title is fixed
* Version is fixed
Closes #376

Fix title on archive download page

---

pages/app/index.ftl
pages/blog.ftl
pages/extensions.ftl
pages/guides.ftl
pages/index.ftl
resources/css/keycloak.css

This fixes some of the usability problems. 
The strategy for the background image: 
* Not show the background image if a person has chosen to see high contrast. Instead use the fallback color "bg-dark" on the start page, and "bg-light" on all other pages. 
* For standard users, increase the legibility by adding a shadow. 
The page now looks like this for regular users: 
When increased contrast has been chosen, it looks like this: 
It now reports for a local build significantly fewer errors. The remaining contrast problems with the links will be handled in a separate PR.
See https://developer.chrome.com/docs/devtools/rendering/emulate-css/ on how to emulate those settings. 
Wave is available as a chrome plugin to run the tests locally: https://wave.webaim.org/extension/
Closes #354

Improve accessibility of the start page

---

resources/css/keycloak.css

This adds a media query and only applies the padding on the `.kc-app` element for rather large screens.
**Before:**
**After:**

Improve test application in smaller breakpoints

---

README.md
resources/css/keycloak.css

This fixes the layout of the tables, as experienced for example on https://www.keycloak.org/server/db
Old layout, missing a proper table heading and too much distance at the bottom of the table cells: 
New layout after CSS changes:

Updates layout of tables in the Keycloak guides

---

pages/community.ftl

Brings back the link to the revived Discourse forum, which was removed with https://github.com/keycloak/keycloak-web/pull/405
/cc @abstractj

Add link to Discourse forum again

---

guides/securing-apps/traefik-hub.adoc

Similar to other external apps, add [Traefik Hub](https://traefik.io/traefik-hub/) API management to the "Securing applications" section of the guides: https://www.keycloak.org/guides#securing-apps

Add Traefik Hub to the guides

---

static/2023/11/kubecon-chicago.html

This redirects from a link share in the KubeCon keynote video `https://www.keycloak.org/2023/11/kubecon-chicago` to the already published blog post.

Redirect from pre-shared link to blog post

---

pages/guides.ftl
resources/css/keycloak.css
src/main/java/org/keycloak/webbuilder/Guides.java
src/main/java/org/keycloak/webbuilder/Links.java
src/main/java/org/keycloak/webbuilder/builders/GuideBuilder.java
src/main/java/org/keycloak/webbuilder/builders/ResourcesBuilder.java

Merge this only after:
* keycloak/keycloak#24913 has been merged
* Keycloak 23 has been released
Related to keycloak/keycloak#24844

Adding a Keycloak High Availability section to Keycloak's docs

---

guides/securing-apps/traefik-hub.adoc

Traefik Hub's documentation has been remade with a new docs website; thus, the previous link moved.
cc @svx
Original PR for reference: https://github.com/keycloak/keycloak-web/pull/420

Fix Traefik Hub documentation link

---

src/main/java/org/keycloak/webbuilder/utils/FreeMarker.java
templates/template.ftl

Add canonical URLs to all generated pages

---

pages/blog-archive.ftl
static/robots.txt
templates/documentation-11.ftl

This change prevents hits in the Google search without content like the following: 
See https://support.google.com/webmasters/answer/7489871?hl=en#zippy=%2Cthis-is-my-site%2Cthe-page-is-blocked-by-robotstxt for the explanation.
I'll create a follow-up issue to add canonical URLs to all old docs, so the content will eventually redirect to the latest versions.
Closes #460

The no-index functionality works only if the pages are allowed to be crawled

---

blog/2024/keycloak-at-kubecon-eu-2024-recap.adoc

A short recap of Keycloak usage at KubeCON / CloudNativeCon EU 2024 in Paris.

KubeCON24 recap

---

templates/rss.ftl

This error appeared in the search console. All other feed URLs are already pointing to the canonical URLs.

Avoid Google complaining that the RSS feed contain a URL that is not a canonical link on the page

---

templates/template.ftl

Closes #465
At the time of writing this, Keycloak has 20277 GitHub stars.
This adds the widget at different breakpoints: 
There is also the option to add this as an embedded SVG, where the icon links to the GitHub repo, and the number of stars links to the stargazers list. I decided against it as an image is simpler to layout and more control over the link. This might be a precaution if the shields service should be hacked.

Adding GitHub stars to the Keycloak homepage

---

blog/2024/persistent-user-sessions-in-preview.adoc

This announces the persistent sessions feature in Keycloak's blog.
It should allow us to get more feedback on our preview feature.

Announcing persistent sessions preview feature

---

pages/security.ftl

Adds a new section to the 'Security Policy' page outlining the requirements for reporting security issues from automated security scanners, specifically the need to provide a minimal and reproducible example specifically for Keycloak that can actually be exploited.
This also refines the section on reporting issues in general to emphasize the need to test against the latest stable version of Keycloak, as well as the need to provide a minimal an reproducible example.

Add instructions to the Security Policy for automated scanners

---

guides/securing-apps/apisix.adoc
guides/securing-apps/krakend.adoc
guides/securing-apps/quarkus.adoc
guides/securing-apps/traefik-hub.adoc
guides/securing-apps/wildfly.adoc
src/main/java/org/keycloak/webbuilder/Guides.java

Closes #31330
Little changes needed with keycloak PR https://github.com/keycloak/keycloak/pull/31472 to create the new `securing-apps` section in the guides. Sending as draft for now.

Move saml documentation to guides

---

src/main/java/org/keycloak/webbuilder/Guides.java

Closes keycloak/keycloak#31569
Adding the line to also add into `securing-apps` the guides in keycloak. I have checked that with current version the external guides are present, and using `-Dversion.keycloak=999.0.0-SNAPSHOT` both external and the ones in keycloak are there.

Changes to add securing-apps guides in keycloak

---

extensions/client-authorization.json

The [repository](https://github.com/cloudtrust/keycloak-authorization) states: "This repository has been archived by the owner on Jul 21, 2022. It is now read-only."
So I think it is time to remove it.
A replacement is probably https://github.com/sventorben/keycloak-restrict-client-auth which is already listed in the extensions as "restrict client auth": https://www.keycloak.org/extensions.html

The client-auth extension was archived by its authors

---

extensions/bundid.json

This extension was open sourced because a lot of german organizations need to integrate german federal IDP "BundID", which is actually not that trivial (because of some non-standard parts of BundID specification).

Add community-extension: BundID IDP integration

---

static/high-availability/deploy-aws-route53-failover-lambda.html
static/high-availability/deploy-aws-route53-loadbalancer.html
static/high-availability/operate-failover.html
static/high-availability/operate-network-partition-recovery.html
static/high-availability/operate-switch-back.html
static/high-availability/operate-switch-over.html

Do not merge until KC26 has been released.
Closes https://github.com/keycloak/keycloak/issues/31837

Redirect from old HA guide pages present in KC25 which are no longer available in KC26

---

pages/community.ftl

In response to [this comment](https://github.com/keycloak/keycloak/pull/32385#pullrequestreview-2359572507), I created a PR to post community meeting information on the community site.
And I added the OAuth SIG Monthly meeting information.
@stianst

Add community meeting information to community.ftl

---

extensions/keycloak-external-claim-mapper.json

Hello, keycloak maintainers!
I developed extension and would like to propose to include it to https://www.keycloak.org/extensions. It is almost same as https://github.com/groupe-sii/keycloak-json-remote-claim
I made couple of improvements.
- Added user token auth, jsonpath transform and some other configurations, including all features from JSON Remote claim Mapper for Keycloak
- Tested with last keycloak release 25.0.0
- Repository contains all test tools including remote api stub, that helped me alot during debugging my keycloak integration.
I was really enjoying using keycloak in my projects, so i would like to contribute to it. Please take a look.

Add external claim mapper extension to extensions page

---

extensions/keycloak-mfa-plugins.json

Hello Keycloak Team,
Our organization would like to share a collection of MFA extensions with the Keycloak community. We're excited to contribute and would appreciate any feedback you may have.
The project includes three extensions:
- SMS Authenticator: An implementation of the Authenticator SPI for SMS-based MFA, inspired by [dasniko’s 2FA SMS authenticator](https://github.com/dasniko/keycloak-2fa-sms-authenticator).
- Enforce MFA Authenticator: Supports the scenario where users authenticate with a second factor. If neither is available, the user can choose to register one. Based on [this Keycloak PR](https://github.com/keycloak/keycloak/pull/17494).
- Native App MFA Integration: Enables a dedicated mobile app as an MFA method, inspired by the [Action Token Authenticator …

Add community-extension: MFA Plugin Collection

---

blog/2024/preview-keycloak-test-framework.adoc

Closes [#32399](https://github.com/keycloak/keycloak/issues/32399)

Preview - Keycloak Test Framework

---

extensions/keycloak-openfga-event-publisher.json

Hello Keycloak maintainers,
I would like to contribute a Keycloak extension that helps synchronize events from Keycloak to the [OpenFGA](https://github.com/openfga) platform. Using this extension, I have also created the following workshop and articles (detailed below) to provide examples of how to transition from traditional authorization models like RBAC or GBAC to ReBAC for Fine-Grained Authorization (FGA).
- [Workshop: Keycloak integration with OpenFGA for Fine-Grained Authorization at Scale (ReBAC)](https://github.com/embesozzi/keycloak-openfga-workshop)
- [Article: Keycloak integration with OpenFGA (based on Zanzibar) for Fine-Grained Authorization at Scale (ReBAC)](https://embesozzi.medium.com/keycloak-integration-with-openfga-based-on-zanzibar-for-fine-grained-authorization-at-scal …

Add community extension Keycloak OpenFGA Event Publisher

---

.github/ISSUE_TEMPLATE/bug.yml
pages/404.ftl

This adds a 404-page, and also suggest a new bug template.

Adding a 404 page with the option to create a broken link issue

---

guides.yaml
pom.xml

Closes #550
Draft to download and unzip the `keycloak-nodejs-connect` guides into the target directory and add those guides for the generation in the web. It uses the `download-maven-plugin` to do that. It's a draft because a final release in the `keycloak-nodejs-connect` is needed with the guides zip. Right now it is using `nightly` but I think this is not OK either because keycloak-rel is also creating a nightly tag without the guides zip.

Consume keycloak-nodejs-connect guides

---

README.md
package.json
pages/404.ftl
resources/js/redirect.js
resources/redirects
src/main/java/org/keycloak/webbuilder/builders/AppBuilder.java

Add basic redirect support

---

extensions/export-endpoint.json
extensions/keycloak-connect-graphql.json

These community extensions are archived and not relevant anymore. They should be removed from the list. 
@ahus1 Could you please check it? Thanks!

Remove archived community extensions

---

templates/downloads-211.ftl
templates/downloads-23.ftl
templates/downloads-24.ftl
versions/keycloak/21.1.0.json
versions/keycloak/21.1.1.json
versions/keycloak/21.1.2.json

Downloads page has wrong Keycloak Javascript Adapter artifacts file names generated
> Note: SHA1 checksums are not generated, but it has to be fixed on different repository.
Closes #512

Downloads page has wrong Keycloak Javascript Adapter artifacts file names generated

---

pages/extensions.ftl
pages/guides.ftl
pages/nightly/guides.ftl
resources/css/keycloak.css

Closes #581
Proposed changes:
- Let the background in the guides section to be fixed to the screen
- For better readability and categorization, added a block containing all guides in the category
PS: it might be even nice to increase border radius for all buttons, labels and even these categories for some time to show to current visitors some action as the project is still alive :P IMO, it has some psychological effect 
Before: 
https://github.com/user-attachments/assets/93cc0495-7734-4586-aa7c-6cc871df0a49
After:
https://github.com/user-attachments/assets/97d05f29-5a71-44f3-9cbe-d1a2a515ce09

Low resolution background image in guides

---

extensions/tiktok-idp.json

I have created a custom SPI to integrate TikTok as an IDP into Keycloak. It would be great to see it listed here.
See: https://github.com/mpowr-it/keycloak-tiktok

Add TikTok IDP extension

---

extensions/keycloak-app-passwords.json

Adds keycloak-app-passwords extension to the extension list.
- Repo: https://github.com/radicallyopensecurity/keycloak-app-passwords
Fixes: https://github.com/keycloak/keycloak-web/issues/602

Include Keycloak App Passwords in extensions

---

templates/downloads-21.ftl
templates/downloads-211.ftl
templates/downloads-22.ftl
templates/downloads-23.ftl
templates/downloads-24.ftl

Closes #621
The old link is for downloading the source code as a ZIP from the `latest` branch, so it can simply be updated to point to download the ZIP of the `main` branch source code (like clicking the "Code -> Download ZIP" button on the keycloak-quickstarts GitHub repo page with the `main` branch selected).

Update keycloak-quickstarts download link

---

extensions/kcwarden.json

As requested in https://github.com/iteratec/kcwarden/issues/83, I am suggesting to add [kcwarden](https://github.com/iteratec/kcwarden) to the list of extensions. 
Background: kcwarden is a Keycloak config auditor that checks your Keycloak realm configuration for security issues. You can also create custom rules to check for project-specific invariants ("the role `project-admin` should only be assigned to the Keycloak user group `admins`"), or even add completely custom scanner rules implemented in Python. [See the documentation](https://iteratec.github.io/kcwarden/) for more details (or attend our presentation at KeyConf on thursday ;) ).

Add kcwarden to extension list

---

pages/index.ftl
resources/css/keycloak.css

- Closes #633
---------------------
For wide screens, the gap is used instead of the margin-left; no visible change.
@stianst Could you please check it? Thanks!

News section on frontpage not shown properly on smaller screens

---

templates/template.ftl

The count of GH stars on small screens (phones) looks very disruptive as the navbar's height is large and the kebab menu is floating somewhere down. 
It'd be good to remove the GH stars from the shown navbar header and rather to include it somewhere else. I'd say a nice place might be when opening the menu. 
@ahus1 @stianst Is it ok for you?

Hide disruptive GH stars on small screens
