keycloak/keycloak-web

src/main/resources/resources/css/tabzilla.css
Mixed Content Fix using  Protocol-relative URL
=> Mixed Content Fix

templates/rss.ftl
=> Some feed improvements

blog/keycloak-newsletter-1.ftl
@stianst Can you check if it looks okay ?
=> KEYCLOAK-9670: Skeleton of the newsletter

extensions/japanese-documentation-translation.json
I updated the Japanese documentation translation page.
=> Update extension description for "Japanese documentation translation"

extensions/keycloak-python.json
Added python [keycloak client](https://github.com/akhilputhiry/keycloak-client) to extensions.
=> Added keycloak python client to extensions

templates/rss.ftl
see https://twitter.com/shimabukuro/status/1123137070594027520
=> correct link for guid

extensions/france-connect.json
=> Adding France Connect Extension

blog/keycloak-newsletter-2.ftl
@stianst Could you review ? And also add a new "waiting for contribution" list ?
=> Second newletter

blog/keycloak-cluster-setup.ftl
Reopen https://github.com/keycloak/keycloak-web/pull/58
Modified:
1. Convert the full content of README to the blog.
2. Use the latest Keycloak version.
=> Add keycloak-cluster-setup blog.

blog/keycloak-jdbc-ping.ftl
This is a short follow-up blog post on the clustering features we introduced in our container image.
=> JDBC_PING blog post

templates/header.ftl
=> Remove <#/if>

extensions/hiorgserver-idp.json
=> Added HiOrg-Server IDP extension

extensions/discord-idp.json
Adds discord identity provider extension to the list of community extensions page.
=> Added discord identity provider extension

version-template.json
[KEYCLOAK-14713] (Part of KEYCLOAK-13692) Upgrade to Wildfly "20.0.0.Final"
Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>
**_Note:_** Needs to be merged together with the [code](https://github.com/keycloak/keycloak/pull/7157) and documentation one. Do not merge yet
=> [KEYCLOAK-14713] (Part of KEYCLOAK-13692) Upgrade to Wildfly "20.0.0.Final"

guides/getting-started/getting-started-kube.adoc
Fix typo(Kuberneters -> Kubernetes)
=> Fix typo(Kuberneters -> Kubernetes)

version-template.json
[KEYCLOAK-16097] (Part of KEYCLOAK-15692) Upgrade to Wildfly "21.0.0.Final"
Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>
This is now ready for review. Related PRs:
- [Code change](https://github.com/keycloak/keycloak/pull/7463)
- [Documentation change](https://github.com/keycloak/keycloak-documentation/pull/1054)
@abstractj @hmlnarik @mhajas @martin-kanis @mposolda @pedroigor @pskopek @slaskawi @stianst @vmuzikar @vramik PTAL once got a chance
Thanks!
Jan
=> [KEYCLOAK-16097] (Part of KEYCLOAK-15692) Upgrade to Wildfly "21.0.0.Final"

guides/getting-started/getting-started-zip.adoc
The link to Jboss download site is broken
=> Fix download link in getting-started-zip.adoc

extensions/restrict-client-auth.json
Please add my open source extension to the list of community extensiosn.
=> Add community extension "Restrict Client Auth"

pages/security.ftl
=> Update security policy

guides/securing-apps/apisix.adoc
Hi @stianst ,
As discussed in email, I would like to add Apache APISIX integration in the Getting-Started section.
=> Add Apache APISIX integration

pages/community.ftl
=> Update links to GH issues

config.json, src/main/java/org/keycloak/webbuilder/Config.java, src/main/java/org/keycloak/webbuilder/Links.java
=> Fixes double slash in links

templates/downloads-18.ftl
=> Remove old Tomcat and Jetty adapters from downloads

pages/index.ftl, resources/css/keycloak.css, templates/template.ftl
=> Fix frontpage layout on small screens, and setting max-width for images in articles

pages/getting-started.ftl
=> Fix badges on getting started guides not showing

pages/blog.ftl, pages/extensions.ftl, pages/getting-started.ftl
=> Make cards for guides, blog and extensions clickable

pages/app/index.ftl, pages/documentation-archive.ftl, pages/downloads-archive.ftl, src/main/java/org/keycloak/webbuilder/AutoBuilder.java, templates/template.ftl
=> Remove CSP header for test app

src/main/java/org/keycloak/webbuilder/AutoBuilder.java, src/main/java/org/keycloak/webbuilder/Context.java, src/main/java/org/keycloak/webbuilder/Guides.java, src/main/java/org/keycloak/webbuilder/builders/GuideBuilder.java, templates/guide-entry.ftl
=> Build guides in AutoBuilder

pages/app/index.ftl
=> Fix username not displayed

resources/css/keycloak.css, resources/js/guide.js, resources/js/guides.js, templates/guide-entry.ftl
=> Add search and filter to all-configuration server guide

src/main/java/org/keycloak/webbuilder/Guides.java, templates/documentation-9.ftl, templates/downloads-19.ftl, version-template.json
=> Update default distribution to Quarkus on website

guides/getting-started/getting-started-docker.adoc, guides/getting-started/getting-started-kube.adoc, guides/getting-started/getting-started-openshift.adoc, guides/getting-started/getting-started-operator-kubernetes.adoc, guides/getting-started/getting-started-operator-openshift.adoc, guides/getting-started/getting-started-podman.adoc, guides/getting-started/getting-started-zip.adoc, guides/getting-started/pinned-guides, src/main/java/org/keycloak/webbuilder/Guides.java
=> Add support for pinning guides to the top

guides/getting-started/getting-started-podman.adoc, guides/getting-started/getting-started-zip.adoc, guides/includes/getting-started/create-admin-localhost.adoc, guides/includes/getting-started/next.adoc, guides/includes/getting-started/start-keycloak-container.adoc, guides/includes/getting-started/start-keycloak-localhost.adoc, guides/securing-apps/vue.adoc
Updated ZIP and containers. The Kubernetes and OpenShift guides doesn't need updating afaik, but rather only the YAML files need updating, which are covered by https://github.com/keycloak/keycloak-quickstarts/issues/285
Closes #264
=> Update getting started guides to Quarkus dist

resources/css/keycloak.css, templates/guide-entry.ftl
=> Update styling for guides

guides/migration/migrating-to-quarkus.adoc, src/main/java/org/keycloak/webbuilder/Guides.java, src/main/java/org/keycloak/webbuilder/Links.java
Do NOT merge until after Keycloak 17 is released
Closes: #274
=> Add migration from WF to Quarkus guide

guides/getting-started/getting-started-docker.adoc
Addresses https://github.com/keycloak/keycloak-web/issues/279
=> Update links in docker guide

guides/migration/migrating-to-quarkus.adoc
Also fixing a link and formatting.
Closes #283
=> Add section on how to add the initial user in Quarkus distribution.

guides/getting-started/getting-started-openshift.adoc
closes keycloak/keycloak#10569
=> apply quarkus changes to openshift getting started guide

src/main/java/org/keycloak/webbuilder/Guides.java, src/main/java/org/keycloak/webbuilder/Links.java
Resolves #289 
The structure reflects what tracked down here: https://github.com/keycloak/keycloak/issues/10739
A more generic approach have been implemented in #293
=> New Operator documentation structure

.github/workflows/publish.yml, .github/workflows/test.yml, README.md, pom.xml
=> Include server guides by default, and update instructions to use 999-SNAPSHOT

guides/migration/migrating-to-quarkus.adoc
Resolves: https://github.com/keycloak/keycloak/issues/10795
=> Operator migration guide

guides/getting-started/getting-started-operator-kubernetes.adoc, guides/getting-started/getting-started-operator-openshift.adoc
Resolves #292 
This is the result:
and:
=> Refer to the Wildfly distribution in the operator guides

resources/css/keycloak.css, templates/blog-entry.ftl, templates/guide-entry.ftl, templates/template.ftl
=> Bold section headings

extensions/keycloakify.json
[ref](https://github.com/keycloak/keycloak-web/pull/305)  
All right sorry.  
Best regards,
=> Add keycloakify to comunity extentions

templates/downloads-20.ftl, version-template.json
=> Update list of adapters to remove EOL adapters, and mark remaining deprecated adapters

pages/community.ftl
not sure if we should advertise it more in the description, i personally frequent it way more than discourse
Closes #314
=> Add link to github discussions

blog/2022/oidc-certifications.adoc
@stianst @tnorimat @andymunro Do you please have a chance to review this? It is draft for the new blog post about OIDC certifications.
=> Blog post about OIDC certifications

add-version.sh
=> Update version for Keycloak guides

blog/2022/storage-map.adoc
=> Fix Infinispan version required for HotRod store

templates/documentation-10.ftl, templates/downloads-21.ftl, version-template.json
=> Remove WildFly distribution from website downloads and documentation links

templates/documentation-10.ftl, templates/documentation-9.ftl
=> Fix links to API docs

blog/2022/operator-crs.adoc
**This has to be merged after https://github.com/keycloak/keycloak-k8s-resources/pull/11**
=> The future of Keycloak Operator CRs

extensions/home-idp-discovery.json
Please add my open source extension to the list of community extensions.
=> Add community extension "Home IdP Discovery"

guides/migration/migrating-to-quarkus.adoc
Fairly certain this sentence intended to state that there is an "inability" to automatically migrate the previous configuration.
=> Correct confusing sentence

resources/css/keycloak.css
Relates to: CIAM-5050
This adds the necessary CSS changes for https://github.com/keycloak/keycloak/pull/17237
=> Change the list features to the format of a description list

src/main/java/org/keycloak/webbuilder/Links.java
=> Fix edit this guide link as they have been moved

README.md, src/main/java/org/keycloak/webbuilder/builders/GuideBuilder.java
Relates to keycloak/keycloak#19547
=> Adding support for sections being named guides upstream

guides/securing-apps/vue.adoc, static/app/app.js
Closes https://github.com/keycloak/keycloak/issues/19932
=> Apply migrations for Keycloak JS

pages/index.ftl
Relates to keycloak/keycloak.github.io#20
=> Fixes typo on Keycloak's start page

blog/2023/sunsetting-discourse.doc
The same content will be shared under the announcement section on GitHub discussions if this blog post is approved.
=> Blog post with the announcement about Sunsetting Discourse

blog/2023/authorization-survey.adoc
=> Blog post for authorization survey announcement

extensions/cassandra-datastore.json
Please add our open source extension to the list of community extensions.
=> Add community extension: cassandra-datastore

src/main/java/org/keycloak/webbuilder/builders/ReleaseNotesBuilder.java
=> Get release notes from applicable release branch

pages/community.ftl
=> Updating contributors section on web page

templates/downloads-22.ftl, version-template.json
=> Remove Wildfly/EAP OIDC and SAML adapter downloads

src/main/java/org/keycloak/webbuilder/builders/ChangelogBuilder.java
=> Add issues with release label to changelog

blog/2023/keycloak-dev-day-24.adoc
Dear Keycloak-Team,
please find a proposal for an event announcement with this pull-request. We want to promote this community event to all enthusiastic Keycloak  users, contributors, maintainers, and so on. The event will happen in february 2024. 
As previously discussed, @ahus1 , please let me know if this is ok to publish.
All the best,
Sebastian
=> announcement of keycloak-dev-day in februrary 2024

templates/downloads-23.ftl, version-template.json
=> Remove Jetty adapter downloads

templates/template.ftl
=> Copyright year update

blog/2024/keycloak-dev-day-videos.adoc
@ahus1 and @srose please review.
=> Keycloak DevDay 2024 videos

templates/downloads-21.ftl, templates/downloads-22.ftl
=> Third part notice for older releases

guides/securing-apps/apisix.adoc, guides/securing-apps/krakend.adoc, guides/securing-apps/quarkus.adoc, guides/securing-apps/traefik-hub.adoc, guides/securing-apps/wildfly.adoc, src/main/java/org/keycloak/webbuilder/Guides.java
This reverts commit dc7b73293504fa9b710861a33d56b0c22a7c87d9.
=> Revert "Move saml documentation to guides"

pages/blog-archive.ftl, pages/blog.ftl, pages/index.ftl, templates/blog-entry.ftl, templates/template.ftl
This should help promote Keycloak's RSS feed to keep people more up-to-date
=> Adding RSS auto-detection to start page and all blog related pages

.github/workflows/publish.yml
=> Nightly rebuild of website

pages/community.ftl, pages/documentation-archive.ftl, pages/documentation.ftl, pages/downloads-archive.ftl, pages/downloads.ftl, pages/nightly/index.ftl, src/main/java/org/keycloak/webbuilder/Links.java, src/main/java/org/keycloak/webbuilder/Versions.java
=> Update nightly release landing page

templates/blog-release-2.ftl, templates/blog-release-3.ftl
=> Fix release notes

templates/documentation-12.ftl, versions/26.0.0.json
=> Fix link to securing apps guide

blog/2024/release-updates.adoc
=> Minor release blog post

blog/2024/keycloak-kubeconf24-na-slc-announcement.adoc
Fixes https://github.com/keycloak/keycloak-web/issues/514
=> Add KubeCon24 NA SLC announcement blog

templates/downloads-21.ftl
=> Fix broken download link for Keycloak JS

LICENSE, LICENSE.txt
=> Create LICENSE with Apache V2

resources/css/keycloak.css
Support https://github.com/keycloak/keycloak/issues/35415
=> Add AsciiDoc formatting for an example block

blog/2024/keycloak-at-kubecon-na-2024-recap.adoc
@ahus1 @ryanemerson Could you please check it? 
The link on the website does not work.
=> Fix typo in link for KubeCon NA 24 recap

blog/2024/keycloak-at-froscon-2024.adoc, blog/2025/keycloak-at-fosdem-2025.adoc
This announces talks and side events.
=> Announce talks and events at FOSDEM

blog/2025/keycloak-client-2604.adoc
Created blog manually, as we don't yet have automated sending of the blog fully ready.
=> Blog for keycloak client 26.0.4 release

resources/css/keycloak.css, src/main/java/org/keycloak/webbuilder/builders/GuideBuilder.java
=> Add anchors to guides

extensions/quarkus-extensions.json
@ahus1 Could you please check it? Thanks!
=> Add community extension: Quarkus/Quarkiverse extensions

.github/workflows/test.yml, extensions/keycloakify.json, pages/extensions.ftl, src/main/java/org/keycloak/webbuilder/Extensions.java, src/main/java/org/keycloak/webbuilder/builders/AbstractBuilder.java, src/main/java/org/keycloak/webbuilder/builders/ChangelogBuilder.java, src/main/java/org/keycloak/webbuilder/utils/GitHubApi.java
Closes #571
- Abstract GitHub API management
- Show how popular these extensions are
- Divide extensions into sections based on their activity (Active, Less active)
https://github.com/user-attachments/assets/423a5838-b8ba-4583-a249-d3b1fb5ae71d
@ahus1 Could you please check it? Thanks!
=> Improve list of community extensions

guides.yaml
part of keycloak/keycloak#33602
=> moving the migration

pages/blog.ftl
=> Add date and author to the footer of a blog post

src/main/java/org/keycloak/webbuilder/builders/ReleaseNotesBuilder.java
Closes keycloak/keycloak#38931
Previous wrong data has been fixed in commits 934c90e750ca2b56c316db078de770ad7f1d9c8c and 78cc0701bda24f503e647c38930627dc07ae2d20
=> Fixing attributes for release notes

extensions/extended-saml-idp.json
Closes #596
Thank you for maintaining the Keycloak project and its comprehensive website. We have developed [an Extended SAML IDP extension](https://github.com/First8/Extended-SAML-IDP) for Keycloak and are excited to contribute to the community by submitting this pull request to include it on the Keycloak extensions page. Please review the proposed changes, and let us know if any adjustments are needed. We appreciate your time and consideration!
=> Included extended SAML-IDP extension to list.

extensions/keycloak-client-webhook.json
`Keycloak Client Webhook` extension to the extension list.
Repo: https://github.com/chintanbuch/keycloak-client-webhook
Closes #605
=> Keycloak Client Webhook Extension

guides.yaml
Closes #608
This can be merged after https://github.com/keycloak/keycloak/pull/39756 is merged.
=> Add UI Customization Guide

add-version.sh, cache/releases/keycloak/26.3.1/gh-release-notes.html
=> Fix link to migration guide in release notes

resources/redirects, src/main/java/org/keycloak/webbuilder/Context.java, src/main/java/org/keycloak/webbuilder/Guides.java, src/main/java/org/keycloak/webbuilder/Links.java, src/main/java/org/keycloak/webbuilder/builders/GuideBuilder.java, src/main/java/org/keycloak/webbuilder/utils/AsciiDoctor.java, templates/guide-entry.ftl
Closes keycloak/keycloak#41585
Signed-off-by: Ryan Emerson <remerson@ibm.com>
=> Support nested guides

.github/actions/linkcheck/action.yml, .github/dependabot.yml, .github/workflows/test.yml, blog/2017/easily-secure-your-spring-boot.ftl, lychee.toml, package.json, pages/404.ftl, pom.xml
Closes keycloak/keycloak#41741
Currently we exclude external links to prevent issues with rate-limiting.
@ahus1 Please review when you get a chance, thanks.
Keycloak branch changes that will eventually be required: https://github.com/keycloak/keycloak/compare/main...ryanemerson:keycloak:41741/linkcheck
=> Automate a broken link check for keycloak-web

pages/community.ftl
=> Add code of conduct section to community page (#644)
